# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad_dec', models.CharField(max_length=255)),
                ('enfermedad_val', models.IntegerField(unique=True)),
                ('enfermedad_act', models.IntegerField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
