# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_pat', models.CharField(max_length=255)),
                ('apellido_mat', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=255)),
                ('fecha_nac', models.DateTimeField()),
            ],
        ),
    ]
