# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tratamiento', '0001_initial'),
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnotico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paciente.Paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tratamiento.Tratamiento')),
            ],
            options={
                'verbose_name_plural': 'Diagnoticos',
                'verbose_name': 'Diagnotico',
            },
        ),
    ]
